import pool from "@/lib/db";
import { json, preflight, withApi } from "@/lib/cors";
import type { Home, PricePoint, School } from "@/lib/types";
import type { NextRequest } from "next/server";

// params is a Promise in the App Router; typed inline so this file does not
// depend on the route types generated by `next typegen`.
type Ctx = { params: Promise<{ id: string }> };

export const GET = withApi(async (_req: NextRequest, ctx: Ctx) => {
  const { id } = await ctx.params;
  const homeId = Number(id);

  if (!Number.isInteger(homeId) || homeId <= 0) {
    return json({ error: "Invalid home id" }, { status: 400 });
  }

  const { rows: homeRows } = await pool.query(
    `SELECT
       h.id, h.address, h.home_url, h.beds, h.baths, h.sqft,
       h.plan_name, h.homesite, h.price, h.was_price, h.price_per_sqft,
       h.status, h.is_hotw, h.price_drop, h.price_drop_amt,
       h.prev_price, h.new_listing, h.spotlight_features,
       h.first_seen_at, h.last_seen_at,
       h.community_id,
       b.name AS builder, b.color_hex AS builder_color, b.base_url AS builder_url,
       co.name AS community, co.is_55_plus, co.url AS community_url,
       ci.name AS city, ci.state
     FROM homes h
     JOIN communities co ON co.id = h.community_id
     JOIN builders b ON b.id = co.builder_id
     JOIN cities ci ON ci.id = co.city_id
     WHERE h.id = $1`,
    [homeId],
  );

  if (!homeRows.length) {
    return json({ error: "Home not found" }, { status: 404 });
  }

  const home = homeRows[0];

  const { rows: schoolRows } = await pool.query(
    `SELECT s.name, s.grades, s.type, s.district, s.rating_gs,
            s.rating_niche, s.url, cs.distance, cs.approximate
     FROM community_schools cs
     JOIN schools s ON s.id = cs.school_id
     WHERE cs.community_id = $1
     ORDER BY s.rating_gs DESC, s.name`,
    [home.community_id],
  );

  const { rows: historyRows } = await pool.query(
    `SELECT old_price, new_price, drop_amt, drop_pct, drop_source, changed_at
     FROM price_history
     WHERE home_id = $1
     ORDER BY changed_at DESC
     LIMIT 50`,
    [homeId],
  );

  return json({
    ...(home as unknown as Home),
    schools: schoolRows as unknown as School[],
    price_history: historyRows as unknown as PricePoint[],
  });
});

export async function OPTIONS() {
  return preflight();
}
